name: AsteorEffects
main: com.afoxxvi.asteoreffects.AsteorEffects
version: 0.1
api-version: 1.13
commands:
  asteoreffects:
    description: AsteorEffects command
    usage: /asteoreffects
    aliases: [ ae ]
permissions:
  asteoreffects.use:
    description: Allows the player to use AsteorEffects
    default: op
depend:
  - KotlinLib